// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  // schema: "prisma-postgre/schema.prisma",
  schema: "prisma-mysql/schema.prisma",
  migrations: {
    // path: "prisma-postgre/migrations",
    path: "prisma-mysql/migrations",
    seed: "tsx prisma-mysql/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});